name: Run Tests

on:
  pull_request:
      branches:
        - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          working-directory: generatorreceiver

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - uses: actions/checkout@v3

      - name: Run Unit Tests
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - uses: actions/checkout@v3
      - run: make build